name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Start web server
        run: |
          npm start &
          # Optionally wait for the server to start
          sleep 10
        # Adjust the sleep duration based on how long your server needs to start

      - name: Wait for server to be available
        run: npx wait-on http://localhost:4200
        # Adjust the URL and port based on your server configuration

      - name: Run Cypress tests
        run: npx cypress run --config video=true
        continue-on-error: true

      - name: Check video creation
        run: |
          echo "Checking for videos:"
          ls -la cypress/videos
          find cypress/videos -name "*.mp4"

      - name: Check screenshot creation
        run: |
          echo "Checking for screenshots:"
          ls -la cypress/screenshots
          find cypress/screenshots -name "*.png"

      - name: Display Cypress run logs
        run: |
          echo "Cypress run logs:"
          if [ -f cypress.log ]; then
            cat cypress.log
          else
            echo "cypress.log not found"
          fi

      - name: Archive test videos
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos
          if-no-files-found: warn

      - name: Archive test screenshots
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          if-no-files-found: warn
