name: Cypress Tests and Component Check

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm ci

      - name: Start web server
        run: |
          npm start &
          sleep 10

      - name: Wait for server to be available
        run: npx wait-on http://localhost:4200

      - name: Run Cypress tests
        run: npx cypress run --config video=true
        continue-on-error: true

      - name: Check video creation
        run: |
          echo "Checking for videos:"
          ls -la cypress/videos || echo "cypress/videos directory not found"
          find cypress/videos -name "*.mp4" || echo "No video files found"

      - name: Check screenshot creation
        run: |
          echo "Checking for screenshots:"
          find cypress -name "screenshots" || echo "cypress/screenshots directory not found"
          ls -la cypress/screenshots || echo "cypress/screenshots directory not found"
          find cypress/screenshots -name "*.png" || echo "No screenshot files found"

      - name: Check for new components
        id: check-components
        run: |
          # List components in the source directory
          find src/components -type f -name "*.js" | sed 's/src\/components\///' | sed 's/\.js$//' > new_components.txt

          # List test files
          find cypress/integration -type f -name "*.spec.js" | sed 's/cypress\/integration\///' | sed 's/\.spec\.js$//' > tested_components.txt

          # Compare components with tests
          comm -23 <(sort new_components.txt) <(sort tested_components.txt) > missing_tests.txt

          echo "New components:"
          cat new_components.txt
          echo "Tested components:"
          cat tested_components.txt
          echo "Missing tests:"
          cat missing_tests.txt

          if [ -s missing_tests.txt ]; then
            echo "Some components are missing tests!"
          else
            echo "All components have tests."
            rm missing_tests.txt || true
          fi

      - name: Archive test videos
        uses: actions/upload-artifact@v4  # Updated to v4
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos
          if-no-files-found: warn

      - name: Archive test screenshots
        uses: actions/upload-artifact@v4  # Updated to v4
        if: always()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          if-no-files-found: warn

      - name: Archive missing tests report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: missing-tests-report
          path: missing_tests.txt
          if-no-files-found: warn
