name: Cypress Tests and Component Check

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm ci

      - name: Start web server
        run: |
          npm start &
          sleep 10

      - name: Wait for server to be available
        run: npx wait-on http://localhost:4200

      - name: Run Cypress tests
        run: npx cypress run --config video=true
        continue-on-error: true

      - name: Check video creation
        run: |
          echo "Checking for videos:"
          ls -la cypress/videos || echo "cypress/videos directory not found"
          find cypress/videos -name "*.mp4" || echo "No video files found"

      - name: Check screenshot creation
        run: |
          echo "Checking for screenshots:"
          find cypress -name "screenshots" || echo "cypress/screenshots directory not found"
          ls -la cypress/screenshots || echo "cypress/screenshots directory not found"
          find cypress/screenshots -name "*.png" || echo "No screenshot files found"

      - name: List all components and test files
        run: |
          echo "Listing all component files in src/app:"
          find src/app -type f -name "*.js"

          echo "Listing all test files in cypress/e2e:"
          find cypress/e2e -type f -name "*.cy.js"

      - name: Check for untested components
        run: |
          echo "Checking for components without tests:"
          for component in $(git diff --name-only HEAD^ HEAD | grep '^src/app' | grep '.js$'); do
            component_name=$(basename $component .js)
            if ! find cypress/e2e -type f -name "${component_name}.cy.js" | grep -q .; then
              echo "No test found for component: $component_name"
            fi
          done

      - name: Archive test videos
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos
          if-no-files-found: warn

      - name: Archive test screenshots
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          if-no-files-found: warn
