name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2]

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Start web server
        run: |
          npm start &
          sleep 10

      - name: Wait for server to be available
        run: npx wait-on http://localhost:4200

      - name: Run Cypress tests
        run: npx cypress run --config video=true
        continue-on-error: true

      - name: Check video creation
        run: |
          echo "Checking for videos:"
          ls -la cypress/videos || echo "cypress/videos directory not found"
          find cypress/videos -name "*.mp4" || echo "No video files found"

      - name: Check screenshot creation
        run: |
          echo "Checking for screenshots:"
          find cypress -name "screenshots" || echo "cypress/screenshots directory not found"
          ls -la cypress/screenshots || echo "cypress/screenshots directory not found"
          find cypress/screenshots -name "*.png" || echo "No screenshot files found"

      - name: Display Cypress run logs
        run: |
          echo "Cypress run logs:"
          if [ -f cypress.log ]; then
            cat cypress.log
          else
            echo "cypress.log not found"
          fi

      - name: Archive test videos
        uses: actions/upload-artifact@v4  # Updated to v4
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos
          if-no-files-found: warn

      - name: Archive test screenshots
        uses: actions/upload-artifact@v4  # Updated to v4
        if: always()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          if-no-files-found: warn
