name: Detect New Components Without Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  detect-new-components:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # ดึง git history ทั้งหมด

      - name: Detect new components without tests
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            BASE_SHA=${{ github.event.pull_request.base.sha }}
          else
            BASE_SHA=$(git rev-parse HEAD^)
          fi

          echo "Comparing with base SHA: $BASE_SHA"

          NEW_COMPONENTS=$(git diff --name-only $BASE_SHA ${{ github.sha }} | grep -E "\.component\.ts$" || true)

          if [ -z "$NEW_COMPONENTS" ]; then
            echo "No new components detected."
            exit 0
          fi

          echo "New components detected:"
          echo "$NEW_COMPONENTS"

          COMPONENTS_WITHOUT_TESTS=""
          while IFS= read -r component; do
            component_name=$(basename "$component" .component.ts)
            component_dir=$(dirname "$component")
            cypress_test_e2e="cypress/e2e/${component_name}.cy.ts"
            cypress_test_integration="cypress/integration/${component_name}.spec.ts"
            component_test="${component_dir}/${component_name}.component.spec.ts"

            if [ ! -f "$cypress_test_e2e" ] && [ ! -f "$cypress_test_integration" ] && [ ! -f "$component_test" ]; then
              COMPONENTS_WITHOUT_TESTS="${COMPONENTS_WITHOUT_TESTS}${component}\n"
            fi
          done <<< "$NEW_COMPONENTS"

          if [ ! -z "$COMPONENTS_WITHOUT_TESTS" ]; then
            echo "COMPONENTS_WITHOUT_TESTS<<EOF" >> $GITHUB_ENV
            echo -e "$COMPONENTS_WITHOUT_TESTS" >> $GITHUB_ENV
            echo "EOF" >> $GITHUB_ENV
            echo "Components without tests:"
            echo -e "$COMPONENTS_WITHOUT_TESTS"
          else
            echo "All new components have tests."
          fi

      - name: Create issue for components without tests
        if: env.COMPONENTS_WITHOUT_TESTS
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const componentsWithoutTests = process.env.COMPONENTS_WITHOUT_TESTS.split('\n').filter(Boolean);

            const body = `The following new components are missing tests:

            ${componentsWithoutTests.map(c => `- ${c}`).join('\n')}

            Please add tests for these components.`;

            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'New Angular Components Detected Without Tests',
              body: body
            });
