name: Cypress Tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Create Cypress folders
        run: |
          mkdir -p cypress/videos
          mkdir -p cypress/screenshots

      - name: Check and fix permissions
        run: |
          ls -la cypress
          chmod -R 777 cypress

      - name: List Cypress structure
        if: always()
        run: |
          echo "Cypress folder structure:"
          tree cypress || find cypress

      - name: Archive test videos
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos
          if-no-files-found: warn

      - name: Archive test screenshots
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          if-no-files-found: warn
